apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-eks
  region: us-east-1
  version: "1.21"

iam:
  withOIDC: true

#privateCluster:
#  enabled: true

vpc:
  id: "vpc-0d081894632c001f7"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  subnets:
    private:
      us-east-1a:
          id: "subnet-046d2c9e6a9d71b74"
      us-east-1b:
          id: "subnet-0a717585d45c7196a"


managedNodeGroups:
  - name: test-mng1
    instanceType: t3a.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    subnets:
      - "subnet-06cccd421e4cb2861"
      - "subnet-0bbca0a417b091e14"
      - "subnet-00cb6f469efd88126"
    privateNetworking: true